- name: Check disk usage on /
  hosts: pbx_bk
  gather_facts: no
  tasks:
    - name: Get disk usage
      command: df -h /
      register: disk_usage

    - name: Show disk usage
      debug:
        msg: "{{ inventory_hostname }} (IP: {{ hostvars[inventory_hostname]['ansible_host'] | default(inventory_hostname) }}) => Size: {{ disk_usage.stdout_lines[1].split()[1] }}, Used: {{ disk_usage.stdout_lines[1].split()[4] }}"
